version: '3.6'
services:
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6389:6379"

  api:
    build: ./api
    image: "api:latest"
    container_name: api
    depends_on:
      - redis
    environment:
      - DB_ADDR=redis:6379
      - DB_PASS=
      - APP_PORT=:3000
      - DOMAIN=localhost:3000
      - API_QUOTA=10
    ports:
      - "3000:3000"